name: CI/CD Pipeline

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: setup nodejs and Run install.sh
      run: |
        sudo apt-get update -y
        sudo apt-get install -y python2.7
        npm config set python /usr/bin/python2.7
        npm cache clean -f
        
    - name: Set npm version
      run: echo "NPM_VERSION=$(npm -v)" >> $GITHUB-ENV

    - name: Install npm 
      run: |
       echo "using npm version $NPM_VERSION"
      
    - name: Install dependencies
      run: npm install

    - name: Build the application
      run: npm run build
    
    - name: Configure AWS credentials
      run: |
        echo ${{ secrets.AWS_ACCESS_KEY_ID}} > ~/.aws/credentials
        echo ${{ secrets.AWS_SECRET_KEY}} > ~/.aws/credentials

    - name: Deploy to AWS
      run: |
       aws s3 cp build/ s3://forkbucket/ --recursive

    
             

