name: CI/CD Pipeline

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    env:
      ACTIONS_ALLOW_UNSECURE_RUNNER: true
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_KEY }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        node-version: '16' # Specify the desired Node.js version here

    - name: Setup Node.js and Run install.sh
      run: |
        sudo apt-get update -y
        sudo apt-get install -y python2.7
        npm config set python /usr/bin/python2.7
        npm cache clean -f

    - name: Set npm version
      run: echo "NPM_VERSION=$(npm -v)" >> $GITHUB_ENV

    - name: Install npm
      run: |
       echo "using npm version $NPM_VERSION"

    - name: Install dependencies
      run: npm install

    - name: Build the application
      run: npm run build

    - name: Configure AWS credentials
      run: |
        echo "[default]" > ~/.aws/credentials
        echo "aws_access_key_id = $AWS_ACCESS_KEY_ID" >> ~/.aws/credentials
        echo "aws_secret_access_key = $AWS_SECRET_ACCESS_KEY" >> ~/.aws/credentials

    - name: Deploy to AWS
      run: |
       aws s3 cp build/ s3://forkbucket/ --recursive

