name: CI/CD Pipeline

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    env:
      ACTIONS_ALLOW_UNSECURE_RUNNER: true
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_KEY }}
  
    steps:
       - uses: actions/checkout@8f4b7f84864484a7bf31766abe9204da3cbe65b3
       - uses: actions/checkout@v3
       - uses: actions/checkout@v3.2.0
       - uses: actions/checkout@main

       - name: Set npm version
         run: |
          echo "NPM_VERSION=$(npm -v)" >> $GITHUB_ENV
          echo "python=/usr/bin/python2.7" >> $GITHUB_ENV

       - name: updation
         run: |
          sudo apt-get update
          sudo apt-get install -y python2.7

       - name: Install npm
         run: |
          echo "using npm version $NPM_VERSION"

       - name: Install dependencies
         run: npm install

       - name: Build the application
         run: npm run build

       - name: Configure AWS credentials
         run: |
          echo "[default]" > ~/.aws/credentials
          echo "aws_access_key_id = $AWS_ACCESS_KEY_ID" >> ~/.aws/credentials
          echo "aws_secret_access_key = $AWS_SECRET_ACCESS_KEY" >> ~/.aws/credentials

       - name: Deploy to AWS
         run: |
          aws s3 cp build/ s3://forkbucket/ --recursive

